version: "3"
services:
    swoole:
        container_name: swoole
        image: sd:demo
        volumes:
            - /Users/my/GitHub/swoole-sd:/home/work/server/sd
        ports:
            - "9091:9091"
            - "9092:9092"
            - "9093:9093"
        environment:
            - SD_CONFIG_DIR=docker
        command: php /home/work/server/sd/bin/start_swoole_server.php start --debug
