version: "3"
services:
    swoole:
        container_name: swoole
        image: sd:demo
        volumes:
            - /Users/zqh/GitHub/swoole-sd:/home/work/server/sd
        ports:
            - "9092:9092"
            - "9091:9091"
        command: php /home/work/server/sd/bin/start_swoole_server.php start